// Variable to pass content from index.js file
const index = require('../index.js')

// Function that returns a license badge based on which license is passed in
function renderLicenseBadge(license) {
  if (license !== 'None') {
    return `![GitHub license](https://img.shields.io/badge/license-${license}-blue.svg)`;
  }
  return '';
}

// Function that returns the license link
function renderLicenseLink(license) {
console.log(`${license}`)

  if (`${license}` === "Apache") {
    return `https://opensource.org/licenses/Apache-2.0`
  }
  else if (`${license}` === "Boost") {
    return `https://www.boost.org/LICENSE_1_0.txt`
  }
  else if (`${license}` === "GNU") {
    return `https://www.gnu.org/licenses/gpl-3.0`
  }
  else if (`${license}` === "ISC") {
    return `https://opensource.org/licenses/ISC`
  }
  else if (`${license}` === "MIT") {
    return `https://opensource.org/licenses/MIT`
  }
  else if (`${license}` === "Mozilla") {
    return 'https://opensource.org/licenses/MPL-2.0'
  }
  else if (`${license}` === "Unlicense") {
    return 'http://unlicense.org/'
  }
  else if (`${license}` === "License Not Listed") {
    return 'License Not Listed'
  }
  else {
    return 'No license'
  }
}

// Function that returns the license section of README
function renderLicenseSection(license) {
  return `${renderLicenseBadge(license)}
    ${renderLicenseLink(license)}
  `
}

// Function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}
  
  ## Description
  ${data.description}

  ## Table of Contents
  - [Installation](#installation)
  - [Usage](#usage)
  - [Credits](#credits)
  - [License](#license)
  - [Tests](#tests)
  - [Questions](#questions)

  ## Installation
  ${data.installation}
  
  ## Usage
  ${data.usage}

  ## Credits
  ${data.credits}

  ## License 
  ${data.license}

  ${renderLicenseSection(data.license)}

  ## Tests

  ${data.tests}

  ## Questions
  Github User Name: ${data.username}
  Github Profile: https://github.com/${data.username}

  If you have any questions about my Github Project, please send an email to ${data.email} .

  This README was generated by [README-generator](https://github.com/ChelseaLuevano/M9-ReadMe-Generator)
`;

}

// This allows the data from generateMarkdown function to be used in other files in this program
module.exports = generateMarkdown;
